manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: emmett-rayes
      url-base: https://github.com/emmett-rayes
  projects:
    - name: zmk
      remote: emmett-rayes
      revision: main
      import: app/west.yml
    - name: blank-slate-zmk-module
      remote: petejohanson
      revision: main
  self:
    path: config
